<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="background-murmur"><a href="#background-murmur">Background ( Murmur )</a></h2>
    <p>
      Oracle VirtualBox is <strong>incredibly handy</strong>
       (no, just cuz it&#39;s free) for running multiple simple machines on a single device.
    </p>
    <p>
      Since our lab at Academia Sinica is currently experimenting with handling several network traffic generators,
      we’ve installed multiple VirtualBox instances on our Ubuntu desktops.
    </p>
    <p>
      However, since our Ubuntu desktops need to be accessed remotely through a secure gateway, using typical remote
      desktop apps has proven tricky (SSH tunneling with Remmina tends to fail pretty easily).
    </p>
    <p>
      Reluctantly, we had to figure out a way to manage our VirtualBox machines via the command line interface. That’s
      when we discovered VBoxManage and the guestcontrol feature.
    </p>
    <h2 id="step-by-step-guide"><a href="#step-by-step-guide">Step-by-step Guide</a></h2>
    <p>
      There are so many frustrating pitfalls when setting up this technique, so here’s a step-by-step guide to help you
      avoid wasting your time! (Though, honestly, our time feels pretty worthless sometimes. ☺️)
    </p>
    <h3 id="prerequisites"><a href="#prerequisites">Prerequisites</a></h3>
    <p>
      After installing VirtualBox, make sure the necessary tools are set up by checking if these packages are installed:
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">sudo</span> add-apt-repository universe</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">sudo</span> <span class="token function">apt</span> <span class="token function">install</span> liblzf1 libqt6help6 libqt6statemachine6 libqt6xml6t64 libtpms0</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>If something goes wrong and it fails, you might need to fix any broken packages with this:</p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"><span class="token function">sudo</span> <span class="token function">apt</span> --fix-broken <span class="token function">install</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h3 id="installation"><a href="#installation">Installation</a></h3>
    <p>Next, we need to check whether the virtual machine is set up to accept control commands (or not).</p>
    <p>
      Type this on your <strong>host (not your virtual machine)</strong>
      .
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage guestproperty get <span class="token string">"i-am-device-name"</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>You should see the version number pop up. (Just ignore any fail messages for now.)</p>
    <p><ImgZoom src="/vboxmanage/Screenshot1.png" alt="screenshot1"></ImgZoom></p>
    <p>
      If the version number doesn’t show up, you’ll need to install guestcontrol on the <strong>
        guest (virtual machine)
      </strong>
       itself.
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxControl <span class="token parameter variable">--version</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p>And follow the returning info.</p>
    <p><ImgZoom src="/vboxmanage/Screenshot2.png" alt="screenshot2"></ImgZoom></p>
    <p>Success! We can now control the guest machine using just the command line from the host!</p>
    <h3 id="control"><a href="#control">Control</a></h3>
    <p><strong>List virtual machines.</strong></p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">vboxmanage list vms</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><ImgZoom src="/vboxmanage/Screenshot3.png" alt="screenshot3"></ImgZoom></p>
    <p><strong>Boot up certain virtual machines.</strong></p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">vboxmanage startvm <span class="token string">"i-am-device-name"</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><ImgZoom src="/vboxmanage/Screenshot4.png" alt="screenshot4"></ImgZoom></p>
    <p><strong>Check every guest machine&#39;s status</strong></p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">vboxmanage list vms <span class="token parameter variable">--long</span> <span class="token operator">|</span> <span class="token function">grep</span> <span class="token parameter variable">-e</span> <span class="token string">"Name:"</span> <span class="token parameter variable">-e</span> <span class="token string">"State:"</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><ImgZoom src="/vboxmanage/Screenshot5.png" alt="screenshot5"></ImgZoom></p>
    <h3 id="core-execution"><a href="#core-execution">Core Execution</a></h3>
    <p><strong>Copy a file (or an entire directory recursively) from the host to the guest machine</strong></p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage guestcontrol <span class="token string">"i-am-device-name"</span> copyto --target-directory <span class="token string">"/home/i-am-user-name/test.cc"</span> <span class="token string">"/home/pyjuan91/test.cc"</span> <span class="token parameter variable">--username</span> i-am-user-name <span class="token parameter variable">--password</span> <span class="token number">123456</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><strong>PWD or LS or CD command</strong></p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage guestcontrol <span class="token string">"i-am-device-name"</span> run <span class="token parameter variable">--exe</span> <span class="token string">"/bin/ls"</span> <span class="token parameter variable">--username</span> i-am-user-name <span class="token parameter variable">--password</span> <span class="token number">123456</span> --wait-stdout -- <span class="token string">"/home/i-am-user-name"</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><ImgZoom src="/vboxmanage/Screenshot6.png" alt="screenshot6"></ImgZoom></p>
    <blockquote>
      <p>
        You can find the details of each argument in Oracle’s official documentation. (Or, if you’re feeling
        adventurous, just observe our command and figure it out by analogy!)
      </p>
    </blockquote>
    <p class="text-3xl font-bold">We can see now test.cc is in the guest machine!</p>

    <p>
      <strong>Download GNU c++ compiler</strong>
      Note that if you want to run
      <strong>sudo</strong>
       command, you have to write in shellscript format.
    </p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage guestcontrol <span class="token string">"i-am-device-name"</span> run <span class="token parameter variable">--exe</span> <span class="token string">"/bin/sh"</span> <span class="token parameter variable">--username</span> i-am-user-name <span class="token parameter variable">--password</span> <span class="token number">123456</span> --wait-stdout -- <span class="token parameter variable">-c</span> <span class="token string">"echo '123456' | sudo -S apt install build-essential -y"</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><strong>GCC/G++ Path</strong></p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage guestcontrol <span class="token string">"i-am-device-name"</span> run <span class="token parameter variable">--exe</span> <span class="token string">"/bin/which"</span> <span class="token parameter variable">--username</span> i-am-user-name <span class="token parameter variable">--password</span> <span class="token number">123456</span> --wait-stdout -- <span class="token string">"g++"</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><ImgZoom src="/vboxmanage/Screenshot7.png" alt="screenshot7"></ImgZoom></p>
    <p><strong>Compile and Execute cc file</strong></p>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage guestcontrol <span class="token string">"i-am-device-name"</span> run <span class="token parameter variable">--exe</span> <span class="token string">"/usr/bin/g++"</span> <span class="token parameter variable">--username</span> i-am-user-name <span class="token parameter variable">--password</span> <span class="token number">123456</span> --wait-stdout -- <span class="token string">"/home/i-am-user-name/test.cc"</span> <span class="token string">"-o"</span> <span class="token string">"/home/i-am-user-name/test"</span></div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage guestcontrol <span class="token string">"i-am-device-name"</span> run <span class="token parameter variable">--exe</span> <span class="token string">"/home/i-am-user-name/test"</span> <span class="token parameter variable">--username</span> i-am-user-name <span class="token parameter variable">--password</span> <span class="token number">123456</span> --wait-stdout</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <p><ImgZoom src="/vboxmanage/Screenshot8.png" alt="screenshot8"></ImgZoom></p>
    <h3 id="shut-down"><a href="#shut-down">Shut Down</a></h3>
    <div class="code-block">
      <CodeCopy>
        <pre><code
            class="language-sh">{@html String.raw`<div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage controlvm <span class="token string">"i-am-device-name"</span> acpipowerbutton</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">or</div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content"></div></div><div class="code-line"><div class="code-linenotation"><span class="no-line-number"></span><span class="no-line-diff"></span></div><div class="code-content">VBoxManage controlvm <span class="token string">"i-am-device-name"</span> poweroff</div></div>`}</code></pre>
      </CodeCopy>
    </div>
    <h2 id="wrapping-up-sort-of"><a href="#wrapping-up-sort-of">Wrapping Up (Sort Of)</a></h2>
    <p>
      So yeah, that’s how we’ve been taming our VirtualBox beasts. Power it off with <code class="inline-code-block">
        acpipowerbutton
      </code>
      if you’re feeling polite, or just slam it with
      <code class="inline-code-block">poweroff</code>
       when you’re done messing around.
    </p>
    <p>
      Either way, you’re now a command-line wizard—go forth and conquer those virtual machines! (Or at least fake it
      ‘til you make it, like us. 😉)
    </p>
  </article>
</Post>
